name = "espina-design-abandoned"
main = "abandoned-cart-worker.js"
compatibility_date = "2026-05-24"
workers_dev = true

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "ABANDONED_CARTS"
id = "f40bfc293df9405698bced289901d1c4"
